site_name: Cibersabiduría
site_description: Documentación técnica personal sobre cloud, sistemas, redes y ciberseguridad.
site_url: https://cybershield22.github.io/cibersabiduria/

theme:
  name: material
  language: es
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.expand

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Holidays
        - News
      authors_profiles: true
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
  - meta
  - tags
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

extra:
  social:
    - icon: fontawesome/brands/mastodon
      name: squidfunk on Mastodon
      link: https://fosstodon.org/@squidfunk

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Inicio: index.md
  - Cloud: 
    - Visión general: cloud/index.md
    - Terraform:
      - Introducción: cloud/terraform/index.md
    - Azure: 
      - Computing: 
        - Virtual Marchines: cloud/azure/computing.md
  - Redes: redes/index.md
  - Sistemas: sistemas/index.md
  - Blog:
     - blog/index.md
     - blog/tags.md