site_name: Cibersabiduría
site_description: Documentación técnica personal sobre cloud, sistemas, redes y ciberseguridad.
site_url: https://cybershield22.github.io/cibersabiduria/

theme:
  name: material
  language: es
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.expand
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Modo oscuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo claro

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Holidays
        - News
      authors_profiles: true
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
  - meta
  - tags
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CyberShield22
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/david-botella-nicol%C3%A1s-1735992b2/
  generator: false

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Inicio: index.md
  - Cloud:     
    - Visión general: cloud/index.md
    # - Terraform:
    #   - Introducción: cloud/terraform/intro.md
    #   - Instalación: cloud/terraform/install.md
    - Azure: 
      - Computing: 
        - Virtual Marchines: cloud/azure/computing.md
    # - AWS:
    #   - IAM: cloud/aws/iam.md
    # - Google Cloud Platform:
    #   - Computer Engine: cloud/gcp/computers_engines.md
  - Redes: redes/index.md
  - Linux: linux/index.md
  - Windows: windows/index.md
  - Ciberseguridad: ciberseguridad/index.md
  - Blog:
     - blog/index.md
     - blog/tags.md